# Generated by Django 2.2 on 2019-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('period', models.IntegerField()),
                ('registered_users', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment_method', models.CharField(max_length=500)),
            ],
        ),
    ]
